### ISSUE TITLE
Navgraph resets to start destination after orientation change 

### ISSUE THREAD

**Issue by AndyDavidJoyce** [Zhuinden/Jetpack-Navigation-Multistack-Example#1]
Thanks for the great example Zhuinden! 

I was wondering if you could help. I noticed that in some scenarios the NavGraph resets to the start destination. You can reproduce it following these steps. 

1. Click the "Go To Next Screen" button 
2. Click "Go To Second Fragment" button
3. Change to the second tab 
4. Change orientation to landscape and then back to portrait 
5. Click back to the first tab 

Any thoughts how we can maintain the current destination of each of the tabs NavGraphs?

**Comment by Zhuinden** [comment]
Amazing find. I never thought to try to do 2 consecutive config changes. 

1 config change or 1 process death always worked. I guess relying on `onCreateView` (including `NavHostFragment` being created by `FragmentContainerView`) for anything inside a detached fragment was a mistake.

Fixed. https://github.com/Zhuinden/Jetpack-Navigation-Multistack-Example/commit/a431b5867d7a4e2d632951069fcda2af83cf4954

Thanks for the report.

**Comment by AndyDavidJoyce** [comment]
Thanks for the quick reply and fix Zhuinden!
